require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FailsController do

  # This should return the minimal set of attributes required to create a valid
  # Fail. As you add validations to Fail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "headline" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fails as @fails" do
      fail = Fail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fails).should eq([fail])
    end
  end

  describe "GET show" do
    it "assigns the requested fail as @fail" do
      fail = Fail.create! valid_attributes
      get :show, {:id => fail.to_param}, valid_session
      assigns(:fail).should eq(fail)
    end
  end

  describe "GET new" do
    it "assigns a new fail as @fail" do
      get :new, {}, valid_session
      assigns(:fail).should be_a_new(Fail)
    end
  end

  describe "GET edit" do
    it "assigns the requested fail as @fail" do
      fail = Fail.create! valid_attributes
      get :edit, {:id => fail.to_param}, valid_session
      assigns(:fail).should eq(fail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Fail" do
        expect {
          post :create, {:fail => valid_attributes}, valid_session
        }.to change(Fail, :count).by(1)
      end

      it "assigns a newly created fail as @fail" do
        post :create, {:fail => valid_attributes}, valid_session
        assigns(:fail).should be_a(Fail)
        assigns(:fail).should be_persisted
      end

      it "redirects to the created fail" do
        post :create, {:fail => valid_attributes}, valid_session
        response.should redirect_to(Fail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fail as @fail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fail.any_instance.stub(:save).and_return(false)
        post :create, {:fail => { "headline" => "invalid value" }}, valid_session
        assigns(:fail).should be_a_new(Fail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Fail.any_instance.stub(:save).and_return(false)
        post :create, {:fail => { "headline" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fail" do
        fail = Fail.create! valid_attributes
        # Assuming there are no other fails in the database, this
        # specifies that the Fail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Fail.any_instance.should_receive(:update).with({ "headline" => "MyString" })
        put :update, {:id => fail.to_param, :fail => { "headline" => "MyString" }}, valid_session
      end

      it "assigns the requested fail as @fail" do
        fail = Fail.create! valid_attributes
        put :update, {:id => fail.to_param, :fail => valid_attributes}, valid_session
        assigns(:fail).should eq(fail)
      end

      it "redirects to the fail" do
        fail = Fail.create! valid_attributes
        put :update, {:id => fail.to_param, :fail => valid_attributes}, valid_session
        response.should redirect_to(fail)
      end
    end

    describe "with invalid params" do
      it "assigns the fail as @fail" do
        fail = Fail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fail.any_instance.stub(:save).and_return(false)
        put :update, {:id => fail.to_param, :fail => { "headline" => "invalid value" }}, valid_session
        assigns(:fail).should eq(fail)
      end

      it "re-renders the 'edit' template" do
        fail = Fail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Fail.any_instance.stub(:save).and_return(false)
        put :update, {:id => fail.to_param, :fail => { "headline" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fail" do
      fail = Fail.create! valid_attributes
      expect {
        delete :destroy, {:id => fail.to_param}, valid_session
      }.to change(Fail, :count).by(-1)
    end

    it "redirects to the fails list" do
      fail = Fail.create! valid_attributes
      delete :destroy, {:id => fail.to_param}, valid_session
      response.should redirect_to(fails_url)
    end
  end

end
